-- TODO: ZSH ISSUE -> Move the position of the mode indicators for the prompt to the right hand side
-- TODO: UNIMPORTANT -> Figure out how to sync the kitty terminal color settings to the neovim colorscheme
-- TODO: UNIMPORTANT -> Maybe figure out a way to mark a file from nvimtree? -> Wait until the harpoon mark bug gets fixed
-- TODO: Figure out how to get spider to stop at `)`

-- DONE: Highjack the terminal code from nvterm v3.0 and override the builtin terminal with my own local code
-- DONE: Figure out how to send terminal commands via the code in nvterm v2.0 so I can send commands to the terminal via autocommands
-- DONE: Remove scrolloff from terminal buffer
-- DONE: Fix the annoying tabufline title length bug.
-- DONE: Prevent which key from opening in command mode
-- DONE: Add harpoon icons to tabufline if a that file has been marked by harpoon
-- DONE: Add icons for lazy-lock:  , and luarc.json 
-- DONE: Fix the statusline, e.g. get the color scheme, icons, etc more in sync
-- DONE: Add a setting for folke/todo for DONE:
