return {
  ensure_installed = {
    'clangd',
    'docker_compose_language_service',
    'dockerls',
    'emmet_language_server',
    'eslint',
    'gopls',
    'hls',
    'html',
    'htmx',
    'jsonls',
    'lua_ls',
    'marksman',
    'mdx_analyzer',
    'pyright',
    'rust_analyzer',
    'svelte',
    'tailwindcss',
    'taplo',
    'yamlls',
  },
}
