return {
  ensure_installed = {
    'gitignore',
    'bash',
    'c',
    'comment',
    'cpp',
    'css',
    'dockerfile',
    'go',
    'graphql',
    'html',
    'java',
    'javascript',
    'jsdoc',
    'json',
    'http',
    'hyprlang',
    'lua',
    'luap',
    'luadoc',
    'markdown',
    'markdown_inline',
    'python',
    'query',
    'rasi',
    'regex',
    'ron',
    'rust',
    'sxhkdrc',
    'svelte',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
    'xml',
    'yaml',
    'zig',
  },
  autopairs = {
    enable = true,
  },
  indent = {
    enable = true,
  },
  highlight = {
    enable = true,
    use_languagetree = true,
    additional_vim_regex_highlighting = false,
    disable = function(_, bufnr)
      return vim.api.nvim_buf_line_count(bufnr) > 50000
    end,
  },
}
