return {
  devicon = {
    default = '󰈚',
    c = '',
    css = '',
    dart = '',
    deb = '',
    Dockerfile = '',
    html = '',
    jpeg = '󰉏',
    jpg = '󰉏',
    js = ' ',
    kt = '󱈙',
    lock = '󰌾',
    lua = '',
    mp3 = '󰎆',
    mp4 = '',
    out = '',
    png = '󰉏',
    py = '',
    toml = '',
    ts = '󰛦',
    ttf = '',
    rb = '',
    rpm = '',
    vue = '󰡄',
    woff = '',
    woff2 = '',
    xz = '',
    zip = '',
    ['robots.txt'] = '󰚩',
    ['jsx'] = '',
    ['bun.lockb'] = '󰌾',
    ['.env'] = '',
    ['.development.env'] = '',
    ['eslint'] = '',
    ['.eslintignore'] = '󰫈',
    ['http'] = '󰖟',
    ['makefile'] = '',
    ['.nvmrc'] = '󰎙',
    ['.npmrc'] = '󰎙',
    ['package.json'] = '',
    ['package-lock.json'] = '',
    ['.prettierrc'] = ' ',
    ['.prettierignore'] = ' ',
    ['tags'] = '',
    ['tailwind.config.js'] = '󱏿',
    ['tailwind.config.cjs'] = '󱏿',
    ['tailwind.config.ts'] = '󱏿',
    ['tailwind.config.cts'] = '󱏿',
    ['tsconfig.json'] = '',
    ['tsconfig.node.json'] = '',
    ['tsconfig.test.json'] = '󰙨',
    ['vite.config'] = '󰹭',
    ['.ignore'] = '',
    ['hypr'] = '',
  },
  cmp = {
    Text = '󰉿',
    Method = '󰘧',
    Function = '󰡱',
    Constructor = '',

    Field = '󰜢',
    Variable = '󰫧',
    Property = '󰜢',

    Class = '󰠱',
    Interface = '',
    Struct = '󰙅',
    Module = ' ',

    Unit = '',
    Value = '󰎠',
    Enum = '',
    EnumMember = '',

    Keyword = '󰌋',
    Constant = '󰏿',

    Snippet = '',
    Color = '󰏘',
    File = '󰈚',
    Reference = '󰈇',
    Folder = '󰉋',
    Event = '',
    Operator = '󰆕',
    TypeParameter = '󰊄',

    -- Namespace = '󰌗',
    -- Table = '',
    -- Object = '󰅩',
    -- Tag = '',
    -- Array = '[]',
    -- Boolean = '',
    -- Number = '',
    -- Null = '󰟢',
    -- String = '󰉿',
    -- Calendar = '',
    -- Watch = '󰥔',
    -- Package = '',
    -- Copilot = '',
    -- Codeium = '',
    -- TabNine = '',
  },
}
