---@type LazyPluginSpec
return {
  'nvim-tree/nvim-web-devicons', -- https://github.com/nvim-tree/nvim-web-devicons
  opts = {
    override = {
      default_icon = { icon = '󰈚', name = 'Default' },
      c = { icon = '', name = 'c' },
      css = { icon = '', name = 'css', color = '#2196f3' },
      postcss = { icon = '', color = '#DE4012', name = 'Postcss' },
      dart = { icon = '', name = 'dart' },
      deb = { icon = '', name = 'deb' },
      Dockerfile = { icon = '', name = 'Dockerfile' },
      html = { icon = '', name = 'html', color = '#ff9408' },
      jpeg = { icon = '󰉏', name = 'jpeg' },
      jpg = { icon = '󰉏', name = 'jpg' },
      js = { icon = '  ', name = 'js', color = '#f7e025' },
      kt = { icon = '󱈙', name = 'kt' },
      lock = { icon = '󰌾', name = 'lock' },
      lua = { icon = '', name = 'lua' },
      mp3 = { icon = '󰎆', name = 'mp3' },
      mp4 = { icon = '', name = 'mp4' },
      out = { icon = '', name = 'out' },
      png = { icon = '󰉏', name = 'png' },
      py = { icon = '', name = 'py' },
      toml = { icon = '', name = 'toml', color = '#838383' },
      ts = { icon = '', name = 'ts', color = require('onedark.colors').blue_light },
      vue = { icon = '', name = 'vue' },
      jsx = { icon = '', color = '#ccaa00', name = 'jsx' },
      ['bun.lockb'] = { icon = '󰌾', color = '#fbf0df', name = 'bun.lockb' },
      ['.env'] = { icon = '', color = 'gray', name = '.env' },
      ['.development.env'] = { icon = '', color = 'gray', name = '.development.env' },
      ['.ignore'] = { icon = '', color = '#aaaaaa', name = '.ignore' },
      ['.eslintignore'] = { icon = '', color = '#2c739e', name = '.eslintignore' },
      ['eslint.config.js'] = { icon = '', color = '#2c739e', name = 'Eslintrc' },
      ['.eslintrc'] = { icon = '', color = '#2c739e', name = 'Eslintrc' },
      ['.eslintrc.js'] = { icon = '', color = '#2c739e', name = 'Eslintrc' },
      ['.eslintrc.cjs'] = { icon = '', color = '#2c739e', name = 'Eslintrc' },
      ['.eslintrc.json'] = { icon = '', color = '#2c739e', name = 'Eslintrc' },
      ['.eslintrc.yaml'] = { icon = '', color = '#2c739e', name = 'Eslintrc' },
      http = { icon = '󰖟', color = '#519aba', name = 'Http' },
      ['hypridle.conf'] = { icon = '', color = '#00aaae', name = 'Hypridle' },
      ['hyprlock.conf'] = { icon = '', color = '#00aaae', name = 'Hyprlock' },
      ['hyprpaper.conf'] = { icon = '', color = '#00aaae', name = 'Hyprpaper' },
      makefile = { icon = '', color = '#f1502f', name = 'Makefile' },
      ['.nvmrc'] = { icon = '󰎙', color = '#005500', name = '.nvmrc' },
      ['.npmrc'] = { icon = '󰎙', color = '#007700', name = '.npmrc' },
      ['package.json'] = { icon = '', color = '#e8274b', name = 'PackageJson' },
      ['package-lock.json'] = { icon = '', color = '#7a0d21', name = 'PackageLockJson' },
      ['.prettierrc'] = { icon = '', color = '#b11a7c', name = '.prettierrc' },
      ['.prettierignore'] = { icon = '', color = '#580d3e', name = '.prettierignore' },
      tags = { icon = '', color = '#bbbbbb', name = 'Tags' },
      ['tailwind.config.js'] = { icon = '', color = '#4DB6AC', name = 'tailwind' },
      ['tailwind.config.cjs'] = { icon = '', color = '#4DB6AC', name = 'tailwind' },
      ['tailwind.config.ts'] = { icon = '', color = '#4DB6AC', name = 'tailwind' },
      ['tailwind.config.cts'] = { icon = '', color = '#4DB6AC', name = 'tailwind' },
      ['tsconfig.json'] = { icon = '', color = '#519aba', name = 'tsconfig.json' },
      ['vite.config.cts'] = { icon = '', color = '#7c0e8a', name = 'vite.config.cts' },
      ['vite.config.cjs'] = { icon = '', color = '#7c0e8a', name = 'vite.config.cjs' },
      ['vite.config.js'] = { icon = '', color = '#7c0e8a', name = 'vite.config.js' },
      ['vite.config.ts'] = { icon = '', color = '#7c0e8a', name = 'vite.config.ts' },
    },
  },
}
