---@type LazyPluginSpec
return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  event = 'VeryLazy',
  lazy = vim.fn.argc(-1) == 0,
  init = function(plugin)
    require('lazy.core.loader').add_to_rtp(plugin)
    require('nvim-treesitter.query_predicates')
  end,
  cmd = { 'TSUpdateSync', 'TSUpdate', 'TSInstall' },
  opts = {
    ensure_installed = {
      'bash',
      'c',
      'comment',
      'cpp',
      'css',
      'dockerfile',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'go',
      'graphql',
      'html',
      'http',
      'hyprlang',
      'java',
      'javascript',
      'jsdoc',
      'json',
      'jsonc',
      'lua',
      'ocaml',
      'ocaml_interface',
      'luadoc',
      'luap',
      'markdown',
      'markdown_inline',
      'python',
      'query',
      'rasi',
      'regex',
      'ron',
      'rust',
      'svelte',
      'sxhkdrc',
      'toml',
      'tsx',
      'typescript',
      'vim',
      'vimdoc',
      'xml',
      'yaml',
      'zig',
    },
    indent = { enable = true },
    highlight = {
      enable = true,
      use_languagetree = true,
      additional_vim_regex_highlighting = false,
      disable = function(_, bufnr)
        return vim.api.nvim_buf_line_count(bufnr) > 50000
      end,
    },
    auto_install = true,
  },
  config = function(_, opts)
    require('nvim-treesitter.configs').setup(opts)
  end,
}
